# This defines our starting point
FROM node:15

RUN mkdir /usr/src/app

RUN mkdir /usr/src/app/frontend

WORKDIR /usr/src/app/frontend

#RUN npm install -g @angular/cli

#RUN npm install ngx-toastr -save

#RUN npm install @angular/animations -save

COPY . .
