version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
    angular-service: # The name of the service
       container_name: angularjscontainer  # Container name
       build: ./frontend # Location of our Dockerfile
       volumes: # Volume binding
          - './frontend:/usr/src/app/frontend' 
       ports: 
          - '4300:4300' # Port mapping
       command: > 
          bash -c "npm install -g http-server && http-server -a 0.0.0.0 -p 4300 ./app"

    php-service: # The name of the service
       container_name: phpcontainer  # Container name
       build: ./backend # Location of our Dockerfile
       volumes: # Volume binding
          - './backend:/usr/src/app/backend'
       ports:
          - '8082:8082' # Port mapping
       command: >
          bash -c "cd /usr/src/app/backend/storage && touch database.sqlite && cd /usr/src/app/backend && cp .env.example .env && php artisan migrate && php -S 0.0.0.0:8082 -t public"
